# Render Configuration File
# Created by Meikanda Sivam

services:
  - type: web
    name: ai-ppt-generator
    env: python
    runtime: python-3.12.0
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    healthCheckPath: /health
    plan: free
    region: oregon
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
    maxMemory: 512MB
